version: "3.9"
services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - SECRET_KEY=your-secret-key
      - BASIC_AUTH_USERNAME=admin
      - BASIC_AUTH_PASSWORD=secret
      - SENTRY_DSN=  # leave empty or remove if not using Sentry
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
